### ISSUE TITLE
In 1.12.2 there is no effect, does it mean that it is not supported in older versions?

### ISSUE THREAD

**Issue by xiaochunkun** [vectrix-space/ignite#135]

**Comment by vectrixdevelops** [comment]
It should work. Could you share the command you're using to launch it?

**Comment by xiaochunkun** [comment]
java -Xmx8G -Xms512M -Xss512K -javaagent:./ignite-launcher.jar -Dignite.paper.minecraft=1.12.2 -Dignite.paper.target=io.papermc.paperclip.Paperclip -Dignite.service=legacy_paper -jar ignite-launcher.jar ignite.paper.override=false paper.jar

**Comment by vectrixdevelops** [comment]
The additional flags will no longer be needed in the new version of the game, other than the javaagent. Make sure to follow the new readme for Ignite 1.0.0-SNAPSHOT (you will need to build this yourself until it is released).

**Comment by vectrixdevelops** [comment]
The latest release should help by not requiring the flags. Feel free to join the Discord for help if you're still confused.
