### ISSUE TITLE
Logger Configuration of Launch Jar will not be taken over

### ISSUE THREAD

**Issue by MarkusTieger** [vectrix-space/ignite#136]
You should load the log4j2.xml file from the launch jar, before launching it and reconfiguring it with
`org.apache.logging.log4j.core.config.Configurator.reconfigure(config)`

In Ignite:
![image](https://github.com/vectrix-space/ignite/assets/77546847/4495499e-472f-48c8-aab3-f07fe0399281)

Without Ignite:
![image](https://github.com/vectrix-space/ignite/assets/77546847/1da65a96-a413-4471-b46d-d17789c8f3bf)

**Comment by vectrixdevelops** [comment]
This is fixed in the development version of Ignite (1.0.0-SNAPSHOT) and will be included in the next release. This is a breaking change so make sure to update your mods accordingly.

**Comment by vectrixdevelops** [comment]
Fixed in the latest release: https://github.com/vectrix-space/ignite/releases/tag/v1.0.0
