### ISSUE TITLE
Use with paperspigot

### ISSUE THREAD

**Issue by DefinitlyEvil** [vectrix-space/ignite#21]
Hi is there a way to use it with PaperSpigot? 
Thanks!

**Comment by connorhartley** [comment]
Yes there is. Make sure to follow the launch instructions on the README https://github.com/vectrix-space/ignite#launcher-usage as this is NOT a plugin. If you have any questions, or need any help feel free to join the Discord. https://discord.gg/rYpaxPFQrj

If you are using it to launch Paperclip make sure you also include `-javaagent:./paper.jar` as well as the other Ignite java agent flag.

**Comment by connorhartley** [comment]
This will work with Paperclip as of 0.4.0. Make sure to read https://github.com/vectrix-space/ignite#bootstrap-services for more information.

**Comment by DefinitlyEvil** [comment]
Thx! <3
