### ISSUE TITLE
Java 17 deprecated SecurityManager

### ISSUE THREAD

**Issue by VidTu** [vectrix-space/ignite#71]
## Java 17 warning
Caused by [JEP 411](https://openjdk.java.net/jeps/411)
```
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by space.vectrix.ignite.applaunch.service.PaperclipBootstrapService (file:/D:/Server/ignitetest/srv_ignite.jar)
WARNING: Please consider reporting this to the maintainers of space.vectrix.ignite.applaunch.service.PaperclipBootstrapService
WARNING: System::setSecurityManager will be removed in a future release
```
Server loads normally, but this warning says 'consider reporting this to the maintainers'
## Info
Java: 17 ([Temurin](https://adoptium.net/) 17 build 35 64-bit)
OS: Windows 11 Pro x64
Server: Paper 1.17.1 (Using 'Paperclip' launch mode)
Mods: none
Plugins: none

**Comment by connorhartley** [comment]
Fixed in https://github.com/vectrix-space/ignite/releases/tag/v0.7.0 for 1.18+ use the `paperclip` service. On earlier versions use `legacy_paperclip`, however the warning will still persist. I'm not going to make the same change on legacy.
