### ISSUE TITLE
Relocate bundled libraries for better compatibility

### ISSUE THREAD

**Issue by Exceptionflug** [vectrix-space/ignite#74]
Hello,

since all libraries bundled in this jar will be loaded by the system class loader, reflective access inside plugin shaded versions of the same libraries may break. It is common practice to change the namespace during packaging to ensure class definitions across multiple class loaders are consistent.

Currently I'm experiencing issues when using Guice in another plugin.

Since I'm not that familiar with gradle, I cannot supply a solution on how to do this properly with gradle.

**Comment by connorhartley** [comment]
Since Guice is one of the few API dependencies for mods to use, unfortunately we cannot relocate this. If you can update Guice on your plugins you should do that, otherwise there isn't much more I can do sorry.
